# Generated by Django 3.1 on 2020-08-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200814_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titanic',
            old_name='Pclass',
            new_name='pclass',
        ),
        migrations.AddField(
            model_name='titanic',
            name='hey',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
