# Generated by Django 3.1 on 2020-08-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200816_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titanic',
            name='hey',
        ),
    ]
