# Generated by Django 3.1 on 2020-08-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_titanic_hey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titanic',
            old_name='parch',
            new_name='family',
        ),
        migrations.RemoveField(
            model_name='titanic',
            name='sibsq',
        ),
    ]
